torch.Size([1, 512, 512]) torch.Size([1, 512, 512])
Traceback (most recent call last):
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/train_labeled.py", line 39, in <module>
    segmentations = autoencoder.forward_encoder(image)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/model.py", line 164, in forward_encoder
    x9 = self.U_encoder(x)
         ^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/model.py", line 142, in forward
    x_ = conv(
         ^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/model.py", line 62, in forward
    return self.module(x)
           ^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacity of 10.75 GiB of which 31.62 MiB is free. Process 67428 has 6.60 GiB memory in use. Including non-PyTorch memory, this process has 4.12 GiB memory in use. Of the allocated memory 3.05 GiB is allocated by PyTorch, and 27.76 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
torch.Size([1, 512, 512]) torch.Size([1, 512, 512])
Traceback (most recent call last):
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/train_labeled.py", line 25, in <module>
    optimizerE = torch.optim.Adam(autoencoder.U_encoder.parameters(), lr=0.003)
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DataParallel' object has no attribute 'U_encoder'
torch.Size([1, 512, 512]) torch.Size([1, 512, 512])
Training loss:  tensor(18.2721, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(17.5423, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 0: 0.0
Training loss:  tensor(17.8124, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(17.3119, device='cuda:0')
Training loss:  tensor(17.6186, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(17.2622, device='cuda:0')
Training loss:  tensor(17.4781, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(17.0923, device='cuda:0')
Training loss:  tensor(17.4935, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(17.0489, device='cuda:0')
Training loss:  tensor(17.4236, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.9068, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 5: 0.0
Training loss:  tensor(17.2886, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.8574, device='cuda:0')
Training loss:  tensor(17.2189, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.7753, device='cuda:0')
Training loss:  tensor(17.2234, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.9689, device='cuda:0')
Training loss:  tensor(17.1608, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.6403, device='cuda:0')
Training loss:  tensor(17.0573, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.6438, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 10: 0.0
Training loss:  tensor(17.0334, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.6072, device='cuda:0')
Training loss:  tensor(17.0401, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.5992, device='cuda:0')
Training loss:  tensor(17.0165, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.6839, device='cuda:0')
Training loss:  tensor(17.1466, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.6270, device='cuda:0')
Training loss:  tensor(16.9538, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.5776, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 15: 0.0
Training loss:  tensor(16.9271, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.8433, device='cuda:0')
Training loss:  tensor(16.9571, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.4970, device='cuda:0')
Training loss:  tensor(16.9512, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.7628, device='cuda:0')
Training loss:  tensor(16.8910, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.4770, device='cuda:0')
Training loss:  tensor(16.8189, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.5010, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 20: 0.0
Training loss:  tensor(16.7651, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.4762, device='cuda:0')
Training loss:  tensor(16.7919, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.4569, device='cuda:0')
Training loss:  tensor(16.7663, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3557, device='cuda:0')
Training loss:  tensor(16.7704, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3227, device='cuda:0')
Training loss:  tensor(16.7580, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3945, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 25: 0.0
Training loss:  tensor(16.7544, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.4173, device='cuda:0')
Training loss:  tensor(16.7853, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.4133, device='cuda:0')
Training loss:  tensor(16.6508, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3680, device='cuda:0')
Training loss:  tensor(16.7094, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.4430, device='cuda:0')
Training loss:  tensor(16.7094, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3700, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 30: 0.0
Training loss:  tensor(16.7520, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3755, device='cuda:0')
Training loss:  tensor(16.7124, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3519, device='cuda:0')
Training loss:  tensor(16.7031, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3456, device='cuda:0')
Training loss:  tensor(16.7065, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3849, device='cuda:0')
Training loss:  tensor(16.6175, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.2915, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 35: 0.0
Training loss:  tensor(16.6415, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3262, device='cuda:0')
Training loss:  tensor(16.6108, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.3216, device='cuda:0')
Training loss:  tensor(16.5495, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.2711, device='cuda:0')
Training loss:  tensor(16.6210, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.2123, device='cuda:0')
Training loss:  tensor(16.4471, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.2105, device='cuda:0')
/home/gpufs/users/students/iasd23/iasd23_ainane/master_iasd/data_challenge/env/lib/python3.11/site-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received binary values for label, and continuous values for target
  warnings.warn(msg, UserWarning)
Rand index in epoch 40: 0.0
Training loss:  tensor(16.4229, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.1126, device='cuda:0')
Training loss:  tensor(16.4526, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(16.1020, device='cuda:0')
Training loss:  tensor(16.3184, device='cuda:0', grad_fn=<DivBackward0>)
Validation Error:  tensor(15.9250, device='cuda:0')
